// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO2wtOws65FILF5ZRqItDu_ZGNjrZjMmw',
    appId: '1:553438164636:android:6b1c05e470d1076f6cdf59',
    messagingSenderId: '553438164636',
    projectId: 'astrohanumanta-fbdea',
    storageBucket: 'astrohanumanta-fbdea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVV0jy85ZFFkgH3-PB-g--TDNybYopxFE',
    appId: '1:553438164636:ios:bb4af78c4b34f2ec6cdf59',
    messagingSenderId: '553438164636',
    projectId: 'astrohanumanta-fbdea',
    storageBucket: 'astrohanumanta-fbdea.firebasestorage.app',
    iosBundleId: 'com.astro.hanumanta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEWr6G4Ef4aG2OQAilvdqai-y3wwUOJrk',
    appId: '1:590482927810:ios:7944dcc007b8f1ad97cb5b',
    messagingSenderId: '590482927810',
    projectId: 'book-my-astro',
    storageBucket: 'book-my-astro.firebasestorage.app',
    iosBundleId: 'com.example.astrologerAdminPanel',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4B4jajuSgjc808YT5pKXaOVHGdRjphNA',
    appId: '1:553438164636:web:92b1feec7ef8199a6cdf59',
    messagingSenderId: '553438164636',
    projectId: 'astrohanumanta-fbdea',
    authDomain: 'astrohanumanta-fbdea.firebaseapp.com',
    storageBucket: 'astrohanumanta-fbdea.firebasestorage.app',
    measurementId: 'G-DSJ5CBQZKT',
  );

}